apiVersion: broker.fluidos.eu/v1alpha1
kind: Reservation
metadata:
  name: reservation-impossible
  namespace: default
spec:
  requestedResources:
    cpu: "20"
    memory: "50Gi"
  priority: 30
  requesterID: "user-789"
  duration: "1h"
