apiVersion: broker.fluidos.eu/v1alpha1
kind: Reservation
metadata:
  name: test-real-cluster
  namespace: default
spec:
  requestedResources:
    cpu: "1"
    memory: "2Gi"
  priority: 10
  requesterID: "test-user"
  duration: "30m"
